### ISSUE TITLE
Beyond Castle Wolfenstein crash

### ISSUE THREAD

**Issue by TMS2764** [a2-4am/4cade#630] opened 2024-07-26 01:11 UTC
Beyond Castle Wolfenstein crashes on startup in Total Replay 5.1.

**Comment by frankmilliron** [comment] 2024-07-26 01:33
Setup? It's working in Virtual ][.

**Comment by TMS2764** [comment] 2024-07-26 01:52
It works on a stock Apple IIe platinum. Fails on an Apple IIgs and Apple IIe with a 65C816 processor.

**Comment by a2-4am** [comment] 2024-07-26 13:51
unable to reproduce this under emulation (tried ROM01 and ROM03, using fresh download of Total Replay 5.1 from https://archive.org/details/TotalReplay )
<img width="816" alt="Screenshot 2024-07-26 at 9 48 55 AM" src="https://github.com/user-attachments/assets/55059a61-40de-448c-974c-e5562ab274a4">
<img width="816" alt="Screenshot 2024-07-26 at 9 49 34 AM" src="https://github.com/user-attachments/assets/dd8bea20-0718-468b-befb-f25a0e19de22">

**Comment by TMS2764** [comment] 2024-07-27 16:23
Ok, here is what I have so far. I have an [A2PICO](https://www.tindie.com/products/a2store/hdd-emulator-for-apple2-computers-smd/) board with [Total Replay 5.1](https://archive.org/details/TotalReplay) installed. Looks like the drive emulation firmware [A2retroNET](https://github.com/oliverschmidt/a2retronet) is having issues with Beyond Castle Wolfenstein for some reason. BCW with the A2PICO doesn't work an any system. The rest seems to work fine.

But, during my testing, I found that connecting my [Floppy Emu](https://www.bigmessowires.com/floppy-emu/) to an _Apple IIgs ROM1_, BCW also crashes on startup.

![IMG_1852A](https://github.com/user-attachments/assets/63558bd2-79f7-4d00-ad82-952a94aa1c01)

On that same Apple IIgs ROM1 system, if I install a [Yellowstone](https://www.bigmessowires.com/yellowstone/) disk controller and the Floppy Emu, BCW works properly.

I also tested BCW with the Floppy Emu on an Apple IIgs ROM3, Apple IIe platinum+Liron, Apple IIe+Yellowstone. On those systems BCW was working fine.

**Comment by a2-4am** [comment] 2024-09-09 00:06
Closing as this seems like a hardware-specific failure that we can't do anything about. If you think TR could work around it in some way or if you have more information, please reopen.

**Closed by a2-4am** 2024-09-09 00:06 UTC
