### ISSUE TITLE
Trying on MicroDrive Turbo drive partition

### ISSUE THREAD

**Issue by Lee551** [a2-4am/4cade#52] opened 2019-09-15 20:08 UTC
I don’t have a CFFA3000 but I do have a MicroDrive Turbo in my Rom 01 GS.  I used ADTPRO to image it onto the 3rd of 4 HD partitions.

When I boot up into GS/OS  and run the Launcher.System from A.4AM.Pack had  I see on the screen ‘RUN FROM PARTITION 1-4’

When I boot into GS/OS with SetStart CDEV set to launch Launcher.System I get ‘RUN FROM PARTITION 1-4’

**Comment by peterferrie** [comment] 2019-09-18 21:15
The text was wrong.  It's actually limited to partition 1-2 for now.  That's not specific to the MicroDrive.

**Comment by peterferrie** [comment] 2019-09-19 03:53
Might be fixed by 02d7d2be9358cbb11fef141bada841f4bd59963c.  Waiting for reply from other testers.

**Comment by a2-4am** [comment] 2019-10-07 18:05
Update for those not watching the commit log: we have identified the root cause of this issue and have fixed it in v3 for a majority of games. ~10% of the games require individual updates, and @peterferrie is working through those now.

**Comment by a2-4am** [comment] 2019-12-14 03:45
This is fixed in v3-beta.1

**Closed by a2-4am** 2019-12-14 03:45 UTC
