### ISSUE TITLE
Asteroid Blaster problems

### ISSUE THREAD

**Issue by xandark** [a2-4am/4cade#54] opened 2019-09-18 07:35 UTC
Running Total Replay v2.0-beta2.2mg, I find that when I browse through the game selection ist by pressing the right arrow key 15 times until I come to "Asteroid Blaster by Jordan Mechner", I press Enter, and the screen shows the previous title screen, which was Arkanoid, which is confusing. Then I realize that it is running Asteroid Blaster. But the Asteroid Blaster graphics are corrupted. The vector shapes its drawing are out of whack.

**Comment by a2-4am** [comment] 2019-09-18 18:07
Showing of the previous title screen is now fixed in https://github.com/a2-4am/4cade/commit/aafe2ce134ab374e8d82e4dd31f203e8091376fe

Leaving this issue open so @peterferrie can look into the corrupted graphics.

**Comment by peterferrie** [comment] 2019-09-18 21:19
Can you be more specific about the corrupted graphics?  Sometimes the asteroids are drawn overlapping, but that's true in the original, too.  If it's something else, then I haven't seen it.

**Comment by xandark** [comment] 2019-09-18 23:16
Okay, let me attach some screenshots. This is using Applewin 1.28.6.0...

![Asteroid Blaster 1](https://user-images.githubusercontent.com/5048913/65193324-87e8a680-da2f-11e9-82e3-6403c52eaaf0.jpeg)
![Asteroid Blaster 2](https://user-images.githubusercontent.com/5048913/65193325-87e8a680-da2f-11e9-8e07-519bfa52abe4.jpeg)
![Asteroid Blaster 3](https://user-images.githubusercontent.com/5048913/65193326-87e8a680-da2f-11e9-8933-95731cc5f9dd.jpeg)

**Comment by peterferrie** [comment] 2019-09-19 01:42
Please try AppleWin 1.29 first.  If the problem persists, then please
attach a save-state so that I might be able to trace the source.

**Comment by xandark** [comment] 2019-09-19 06:06
Okay, I tried it again in AppleWin 1.29.2.0 and it still has the same visual glitches. No change.

BTW, in the 3rd photo I attached, I think that's supposed to be the hi-score table that appears after your game is over. That even looks scrambled.

**Comment by xandark** [comment] 2019-09-19 06:11
This is the save state...
[SaveState.aws.yaml.txt](https://github.com/a2-4am/4cade/files/3629670/SaveState.aws.yaml.txt)

**Comment by peterferrie** [comment] 2019-09-19 17:10
Thanks, it's caused by the enhanced IIe mode.
It's likely some undefined opcodes that became defined and have
different effects now.
I can fix that.

**Comment by peterferrie** [comment] 2019-09-19 17:40
An off-by-one branch target in two places in the original game code hit an undefined 6502 opcode that became defined in 65C02.
Fixed in ad328e525cd864f9f04b93ecebea2583eace0d9d.

**Closed by peterferrie** 2019-09-19 17:40 UTC

**Comment by xandark** [comment] 2019-09-19 23:39
ah very good!
