### ISSUE TITLE
Galactic Attack hangs on start

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4cade#595] opened 2024-06-13 05:17 UTC
Shows a message on screen "SYSTEM.PASCAL not found" on //e.

Seems to run properly on a (emulated) ][+.

**Comment by peterferrie** [comment] 2024-06-14 00:29
I can't reproduce it in MAME or AppleWin.  Is it Virtual II?

**Comment by frankmilliron** [comment] 2024-06-14 00:40
Yes

**Comment by peterferrie** [comment] 2024-06-14 01:47
I can't reproduce this in Virtual II.  Please send a save-state.

**Comment by frankmilliron** [comment] 2024-06-14 01:55
Attached. Thanks for looking into it.
[Galactic.viisnapshot.zip](https://github.com/user-attachments/files/15830610/Galactic.viisnapshot.zip)

**Comment by peterferrie** [comment] 2024-06-20 22:01
fixed in f618e901c641a87ac9abcf97e0938ad207611bce.  It needed to see a floppy drive in slot 6.

**Closed by peterferrie** 2024-06-20 22:01 UTC
