### ISSUE TITLE
Apple 2c HGR colour issue.

### ISSUE THREAD

**Issue by ArgGrr** [a2-4am/4cade#274] opened 2020-06-27 07:44 UTC
Hi,

Issue I have noticed with latest 4.0 Alpha. Same happens in build 1841. Running on my 2c.
From the main menu, if I press left/right arrow keys or any alphabet key to search for games, the HGR colours get stuck in green/purple until I press CTRL-RESET.
DHGR images and games not affected it seems.

If the only key I press is ESC to run the screen saver, some transitions will be limited to green/purple, such as the slow pixel white noise style transition. Other transitions, such as the curtains one that close inwards are fine.
Pressing Enter on a full colour transition has mixed results.

Self running demos seem to be in proper colour also.
Pressing Enter on a self-running demo causes the game to start in green/purple mode.

Confused? I am!

**Comment by ArgGrr** [comment] 2020-06-28 02:28
I uploaded a short video showing the demo running for 5 minutes. I didn't start any games, but you can see some transitions are limited to green & purple.
https://github.com/ArgGrr/Apple2cVGA/blob/develop/Screenshots/Total%20Replay%20Alpha%204.m4v

**Comment by sicklittlemonkey** [comment] 2020-07-08 08:23
Pretty sure this will be pulling AN3 low in HIRES which results in Sather's "Undelayed HIRES80" undocumented video mode. See Understanding the Apple //e page 8-22.

**Comment by ArgGrr** [comment] 2020-07-08 13:23
Yeah that seems to be it. I did a small test with this basic program:

```
5 REM Apple 2c Sathers demo
10 HGR2
20 C=8/280
30 FOR I=0 TO 279
40 HCOLOR=I*C
50 HPLOT I,0 TO I,191
60 NEXT
70 GET S$
80 POKE 49246,0: REM $C05E = UNDELAYED
90 GET S$
100 POKE 49247,0: REM $C05F = DELAYED
110 GOTO 70
```

Draws colour bars, and when you press a key the higher colours get "undelayed", or green & purpled.
In AppleWin under 2e emulation, it gets stuck in monochrome after the first cycle but you can see the bit shifting.
Under MAME apple2c emulation, it works as my real hardware does.

**Comment by peterferrie** [comment] 2020-07-08 16:51
It's caused by either our support for the RGB card (if v3 did it), or
as a side-effect of avoiding a certain OpenEmulator bug (if it started
only in builds after March 25).
So when did it start showing up again?

**Comment by sicklittlemonkey** [comment] 2020-07-08 22:49
FB user "Jun Zhu" has posted [this video](https://www.facebook.com/groups/5251478676/?post_id=10160080337403677) and says he tried v3 and v4, but didn't give exact versions.

**Comment by ArgGrr** [comment] 2020-07-08 22:57
Bug introduced somewhere between build 1438 (v3 good) and build 1637 (v4 bad).
First time I noticed was 4 alpha.

**Comment by peterferrie** [comment] 2020-07-08 23:57
One of the builds in the range of 1455-1472 might be the one.
archive.org has those builds.  Please tell me if it's one of those.
1455 is probably fine, 1472 is probably bad, and if so then going back
from 1472 will be faster than going forward from 1455.

**Comment by ArgGrr** [comment] 2020-07-09 00:21
1467 is where it starts going bad.

**Comment by peterferrie** [comment] 2020-07-09 01:24
Thanks.  It's AN2 (not 3) control which we removed in that build.  I
will look at restoring it.

**Comment by ArgGrr** [comment] 2020-07-09 01:27
Thanks! If I can be of any assistance, please let me know.

**Comment by peterferrie** [comment] 2020-07-09 01:42
might be fixed by b48c9172fda1a47c637b602b6babb3a6cf72ec9e

**Comment by griffin9k** [comment] 2020-07-09 02:00
> FB user "Jun Zhu" has posted [this video](https://www.facebook.com/groups/5251478676/?post_id=10160080337403677) and says he tried v3 and v4, but didn't give exact versions.

This video shows it's "Build 1708"

**Comment by ArgGrr** [comment] 2020-07-09 03:27
Yes that seemed to do the trick. I built it under windows, will let it run for a bit and test.
BTW I had an issue building current repository:
`Error - File src\ui.overlay.a, line 103 (Zone <untitled>): Operation not supported: Cannot apply "multiplication" to "string" and "number".`

I fixed it by commenting out the *2:
`         lda   #" "; * 2`

Unsure if this is a typo or some voodoo.

Cheers!

**Comment by peterferrie** [comment] 2020-07-09 17:08
It's voodoo.  I'll replace it with the calculated constant instead.

**Comment by ArgGrr** [comment] 2020-07-10 21:05
Been going through source trying to figure out why DHGR is disabled. Tricky, quite a lot going on. The accelerate/decelerate functions are called when titles are loaded in the background, Is this happening after DHGR mode is being set? The change you made would then turn off DHGR mode, at least on my model.
Would a solution be to not attempt to do any acceleration/decelration actions on models without this capability?

I am also running Rom 4X, but it should still be detected as a IIc.

**Comment by peterferrie** [comment] 2020-07-10 21:55
Acceleration happens during load and unpacking of images, but before
DHGR is turned on to display the image.

> Would a solution be to not attempt to do any acceleration/decelration
> actions on models without this capability?

There are accelerators for the IIc.  We can't detect reliably if one
is present or not, hence the need to do blind acceleration and deal
with the side-effects that it produces.

**Comment by sicklittlemonkey** [comment] 2020-07-11 00:46
It's hard to appreciate the full scope of the code at a glance (fantastic work of course, BTW) but perhaps your statement is overly pessimistic. ; - )

Is an accelerator not detectable by ... acceleration? If at init you tried enabling each (platform relevant) accelerator and then timed some dummy work, you could be more selective from then on. Not trivial, I know, but for the //e up you could use VBL for timing, and for the older models probably the floating bus.

I know, I know. Talk is cheap, show me the code! Well, I've never owned an accelerator, otherwise I might give it a go. I suppose I have a IIgs ...

**Comment by ArgGrr** [comment] 2020-07-11 09:39
I did a hacky fix to the code which seems to work for now, re pull request.

The timing thing sounds good. If you have enough RAM for all the flags! Is there room for 1 bit in the speaker?

**Comment by ArgGrr** [comment] 2020-07-14 09:57
Hi Peter,

I think it's good now! You can close this if you are happy with the fix.

**Comment by peterferrie** [comment] 2020-07-14 17:09
Thanks for letting me know.

**Closed** 2020-07-14 17:09 UTC
