### ISSUE TITLE
Microwave graphical glitches

### ISSUE THREAD

**Issue by a2-4am** [a2-4am/4cade#313] opened 2020-07-26 18:38 UTC
IIgs

**Comment by frankmilliron** [comment] 2020-07-27 05:02
Hmm not seeing this one on my ROM3

**Comment by peterferrie** [comment] 2020-07-27 05:07
I couldn't reproduce it either but I suspect screen-hole damage.

**Comment by frankmilliron** [comment] 2020-07-27 05:35
wonder if different ROM versions use those locations differently for acceleration. What version does LadyAiluros have?

**Comment by peterferrie** [comment] 2020-07-27 16:52
She has a ROM1.

**Comment by peterferrie** [comment] 2020-07-29 17:11
Likely related to #286

**Comment by roughana** [comment] 2020-08-02 05:05
I was unable to reproduce on ROM 3

**Comment by peterferrie** [comment] 2020-08-12 15:36
fixed in 33d00fc978e800c9ca3c5d20b44a27352d767620

**Closed by peterferrie** 2020-08-12 15:36 UTC
Labels: bug, from-stream
