### ISSUE TITLE
Typing letters of the name to get a game has always been problematic

### ISSUE THREAD

**Issue by JDW1** [a2-4am/4cade#557] opened 2024-01-02 09:27 UTC
From the very first version of Total Replay I ever tried, either on an Apple IIe Card, or real Apple IIc, or in the Virtual ][ emulator, typing the first few letters of a game's name to get the program to jump to that game has always been fiddly and hit-and-miss.  It's more MISS than HIT.  Doesn't matter if I use Caps Lock or not.  Doesn't matter how fast or slow I type.  Surely there must be a better way.  I always end up having to press the first letter of the name and then slowly press the arrow keys to try to find the game because like I said, typing more than one letter is problematic.  And if you make a mistake and keep typing, it then beeps at you too.

There really needs to be a visible text field in which we can type the characters of the name and hit return to reliable do searches.

Thanks.

**Comment by philtimmes** [comment] 2024-01-02 17:16
The search field is a nearest match type. The letters you type select the nearest match that has the characters that you typed, in the order you typed them in. It is NOT a full text search.
For instance: GOODNI will bring up Captain Goodnight, IF your configuration supports the game Captain Goodnight.
To get other items that may have the same or nearby letters, you can use the right or left arrow keys.
Additionally, the letters you type are represented by DOTS above the matching letters typed on the title bar at the bottom.
Hopefully this will help you understand.
Assuming that based on this, you can close this.

**Comment by JDW1** [comment] 2024-01-02 18:28
Believe me, I know.  But the games my typing brings up are always hit and miss.  Seems to vary by typing speed as well.  Say for example, I type B-E-T.  Normally, it often brings up games starting with E!  Let's say I want to bring up Double Trouble by typing D-O-U, but it shows me DUNG BEETLES.  After a few more repeated tries at different speeds, it then may find it, but not always.  This happens on a real Apple IIc and in the Virtual ][ emulator.  It's happened for as long as I've used Total Replay.  I've simply never said anything until now.  When I type K-A-R-A to get Karateka, it often brings up Kamikaze instead.  Want Ms. Pacman?  When I type M-S, it always hits Mine Sweep, and yes, I see the two dots, but pressing the back arrow only shows Mazy. I am always forced to press M only and then the arrows to go game-by-game until I find Ms. Pacman manually.

Believe me, I know how it works, and I am reporting that it is hit-and-miss in that it does not work as expected.  This is why I reported it.

You mentioned Captain GOODNIGHT and that GOODNI works.  Indeed that does.  I tried it.  But many people type the first word.  But when you type CAPT, you get Catacombs. 

I could go on and on and on and on, but I think you can now better understand what I mean.

I still feel strongly that search could be improved over what we have now.  That is all I am saying and suggesting.  Thanks.

**Comment by peterferrie** [comment] 2024-01-04 03:16
What you're describing is a symptom of keys being dropped.  "CAPT" gives "Catacombs" only if the 'P' is dropped.  Otherwise, you'd get "Captain Power".  Similarly, "KARA" will give Kamikaze until the 'R' is seen to be pressed.  If it's missed then it will continue to match Kamikaze.
I can reproduce your Kamikaze example in Virtual II if I type quickly enough.  Otherwise, I get Karateka as intended.
The Apple II doesn't buffer keypresses, so if you type quickly enough you'll see dropped keys.
My only suggestion is that you type slower.  This is not specific to TR.

**Closed by peterferrie** 2024-01-04 03:16 UTC

**Comment by JDW1** [comment] 2024-01-04 05:14
Believe me, I have tried typing slower than a turtle could type and there are times when it still doesn’t jump to the right game. 

I also realize the Apple to doesn’t buffer the keys being typed. But what I am proposing is a different way of searching. For example, when someone types any key, could it not be made such that a dedicated search screen will appear and allow the user to type in a string of characters that will be shown to the user on the display and then when they hit Return it will then and only then do the search? That would eliminate any possibility that any characters would be dropped. That’s what I’ve been trying to say anll along.

I think the reason why everyone wants to close this topic as quickly as possible is perhaps because no one other than myself has mentioned this. But that doesn’t mean it’s not a problem. It just means people are too busy or don’t care enough about the issue to say anything about it. I’m one of those people who knows nothing is ever going to improve unless you say something. That’s why when I find a bug in a game, I’m going to report it here, not only for myself, but for the good of everyone else using the software.

Thanks.

**Comment by JDW1** [comment] 2024-01-04 09:18
Peter,

I suspect that you and [philtimmes](https://github.com/philtimmes) wanted to quickly close this topic because you both feel that perhaps I alone am experience this, and for the sake of providing you with user data, I opened a [poll on the Apple II Enthusiasts FaceBook group](https://www.facebook.com/groups/5251478676/posts/10163368288708677/).  It's only been up a few hours, but so far, here are the results...

<img width="696" alt="TotalReplay_POLL" src="https://github.com/a2-4am/4cade/assets/3928027/d652aa9f-9c99-4a4e-aa00-15ef662ff3ed">
.
.

My intent is not to unnecessarily complain or be a pest, but rather to point out who is having issues with the current method of "type blind to search" feature in Total Replay.  As you can see, it is more than just me.  So if there might be any way to offer an improved method of game search, I think the majority of users stand to benefit.

Thanks for your amazing work on Total Reply thus far!

—James Wages

**Comment by peterferrie** [comment] 2024-01-04 17:22
Mitchell unintentionally captures the problem with the poll.  That it's hit or miss can be attributed to multiple things, one of which is that the list is not sorted alphabetically; one of which is the dropped keys; one of which is that multiple games have letters in common, which can result in the "wrong" game being shown first.

The issue was closed because it describes a bug, and its cause is understood and accepted.
If you want to suggest an alternative implementation, then please create a new issue that describe a feature request.
