### ISSUE TITLE
Total Replay v3.0-beta.2 infinite loop

### ISSUE THREAD

**Issue by tomcw** [a2-4am/4cade#108] opened 2020-01-18 12:10 UTC
I was trying Total replay v3.0-beta.2 with AppleWin 1.29.7.0, and got it into a state where it's looping infinitely reading HDD block 0 then block 0x208a (then repeating). I have grabbed an AppleWin save-state and attached it here:

[Total Replay v3.0-beta.2-hang.aws.yaml.zip](https://github.com/a2-4am/4cade/files/4080580/Total.Replay.v3.0-beta.2-hang.aws.yaml.zip)

NB. You need to unzip this if you want to load into AppleWin. It's text, so you can visually inspect it to see the Apple //e config (which is nothing special).

**Details of what I did:** From boot, I only stayed on the main menu. IIRC, I typed "AI" (then watched some Airheart screenshots), then "RA" (then watched some Rampage screenshots). Then it started cycling randomly through game screenshots. I typed "THE" too quickly and it just picked up "TH", but at this point it just got stuck in this loop.

On HGR2, you can see the THIEF screenshot.

I have tried to reproduce it, but can't.

**Comment by peterferrie** [comment] 2020-01-19 22:56
Thanks for the report, the looping occurs when a file can't be located.
Somehow the prefix contains lower-case characters ("Thief") which I
haven't seen before.  Everything is supposed to be in upper-case to
match the filesystem.
The prefix is written in only a couple of places, so hopefully it
won't be hard to track down the cause.

**Comment by peterferrie** [comment] 2020-01-20 05:09
fixed in be9765ca75bcc841c520a4d801e21e4f40bfaa39

**Closed by peterferrie** 2020-01-20 05:09 UTC
